// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-mj9ARBmBWpvsA8njwTyGq9oFUs8rrQg',
    appId: '1:659291753409:web:30e52c8eea07d7d762bd40',
    messagingSenderId: '659291753409',
    projectId: 'esdc-restaurant',
    authDomain: 'esdc-restaurant.firebaseapp.com',
    storageBucket: 'esdc-restaurant.firebasestorage.app',
    measurementId: 'G-HEMRB51B38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1hqBZzd2CqBYRHrhVX9BED0DMFYSwgt0',
    appId: '1:659291753409:android:3d3a3730fb2f8a2662bd40',
    messagingSenderId: '659291753409',
    projectId: 'esdc-restaurant',
    storageBucket: 'esdc-restaurant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgDGhjDjWcopVsV8Jcxw0VoWUpf7c1RpQ',
    appId: '1:659291753409:ios:c8fcb37233157c9662bd40',
    messagingSenderId: '659291753409',
    projectId: 'esdc-restaurant',
    storageBucket: 'esdc-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.restaurantManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgDGhjDjWcopVsV8Jcxw0VoWUpf7c1RpQ',
    appId: '1:659291753409:ios:c8fcb37233157c9662bd40',
    messagingSenderId: '659291753409',
    projectId: 'esdc-restaurant',
    storageBucket: 'esdc-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.restaurantManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-mj9ARBmBWpvsA8njwTyGq9oFUs8rrQg',
    appId: '1:659291753409:web:919716b1e70ff6d562bd40',
    messagingSenderId: '659291753409',
    projectId: 'esdc-restaurant',
    authDomain: 'esdc-restaurant.firebaseapp.com',
    storageBucket: 'esdc-restaurant.firebasestorage.app',
    measurementId: 'G-4DGD0SFDW9',
  );
}
